#ifndef INCLUDED_UTILTIY_MACRO_DEFINITIONS
#define INCLUDED_UTILTIY_MACRO_DEFINITIONS

#define UTILITY_CONCATENATE_MACRO_IMPL(a, b) a##b
#define UTILITY_CONCATENATE_MACRO(a, b) UTILITY_CONCATENATE_MACRO_IMPL(a, b)

#endif // INCLUDED_UTILTIY_MACRO_DEFINITIONS
