simulation:
  end_time: 0.6
  grid_elements: 50
  grid_size: 1.0
  offset: [0.0, 0.0]

solver:
  order: 3
  courant: 0.5
  timeintegrator: Euler

equation:
  equation: advection
  scenario: planar_waves

output:
  start: 0  #s
  step: 0.1 #s