simulation:
  end_time: 1
  grid_elements: 16
  grid_size: 1.0
  offset: [0.0, 0.0]

solver:
  order: 2
  courant: 0.5
  timeintegrator: SSPRK2

equation:
  equation: advection  
  scenario: planar_waves

  
output:
  start: 0 #s
  step: 0.05 #s

amr:
  amr : true
  max_level: 7